version: '3'

services:

    apache:
        image: httpd
        restart: always
        ports:
            - "$NETWORK_MSC_GATEWAY:$PORT_00081_APACHE"
        volumes:
            - "$VOLUME_TIME_SYNC"
            - "$VOLUME_APACHE_HTTPD_CONF"
            - "$PWD/docs/_site:/usr/local/apache2/htdocs"

#        command: "jekyll --help"
#        command: "jekyll new /srv/jekyll/new"
    jekyll:
        image: jekyll/jekyll
        restart: always
        ports:
            - "$NETWORK_MSC_GATEWAY:$PORT_00082_JEKYLL"
        command: "jekyll serve --source /srv/jekyll"
        volumes:
            - "$VOLUME_TIME_SYNC"
            - "$PWD/docs:/srv/jekyll"

networks:
    default:
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: "false"
            com.docker.network.bridge.name: "$NETWORK_MSC_BRIDGE"
        ipam:
            driver: default
            config:
                - subnet: "$NETWORK_MSC_SUBNET"
