description: MSC Kasendorf e.V.
encoding: utf-8
page-post-limit: 5
page-prefix: /docker/
page-root-url: http://www.msc-kasendorf.de
permalink: /:categories/:title/
theme:
timezone: Europe/Berlin
title-homepage: MSC Kasendorf e.V. im ADAC Nordbayern
title: Motorsport

include: ['.htaccess', '.htpasswd']

trenner: ●
