version: '3'

services:

    jekyll:
        image: jekyll/jekyll
        ports:
            - "$NETWORK_JEKYLL_GATEWAY:$PORT_00081_JEKYLL:4000"
#        command: "jekyll --help"
#        command: "jekyll new /srv/jekyll/new"
        command: "jekyll serve --source /srv/jekyll"
        volumes:
            - "$PWD:/srv/jekyll"

networks:
    default:
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: "false"
            com.docker.network.bridge.name: "$NETWORK_JEKYLL_BRIDGE"
        ipam:
            driver: default
            config:
                - subnet: "$NETWORK_JEKYLL_SUBNET"
